# According to
# https://github.com/golang/go/issues/75013
# https://github.com/NixOS/nixpkgs/issues/433688
# our go toolchain now requires macos 12+
c_stdlib_version:          # [osx]
  - '12.3'                 # [osx]
MACOSX_SDK_VERSION:        # [osx]
  - '12.3'                 # [osx]
