{% set version = "0.33.3" %}

package:
  name: tilt
  version: {{ version }}

source:
  url: https://github.com/tilt-dev/tilt/archive/v{{ version }}.tar.gz
  sha256: f69fc7d495cdfa346ba39f353e4e1235b5df7a67a6658e1f43e88648f1f3675d

build:
  number: 0
  script_env:
    - OUTPUT_PATH={{ target_gobin }}tilt{{ target_goexe }}

requirements:
  build:
    - {{ compiler('go') }}

    - {{ compiler('c') }}        # [unix]
    - {{ compiler('cxx') }}      # [unix]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_cxx') }}      # [win]

    - go-licenses
    - sysroot_linux-64 2.17  # [linux64]
  run_constrained:
    - {{ pin_compatible(compiler('c')) }}        # [unix]
    - {{ pin_compatible(compiler('cxx')) }}      # [unix]
    - {{ pin_compatible(compiler('m2w64_c')) }}        # [win]
    - {{ pin_compatible(compiler('m2w64_cxx')) }}      # [win]

test:
  commands:
    - tilt version

about:
  home: https://github.com/tilt-dev/tilt
  license: Apache-2.0
  license_file: LICENSE
  summary: A multi-service dev environment for teams on Kubernetes
  description: |
    Tilt automates all the steps from a code change to a new process: watching
    files, building container images, and bringing your environment up-to-date.

extra:
  recipe-maintainers:
    - joseph-zhong
    - nicks
