{% set version = "0.34.3" %}

package:
  name: tilt
  version: {{ version }}

source:
  url: https://github.com/tilt-dev/tilt/archive/v{{ version }}.tar.gz
  sha256: 82da26266847532442ec1fe427105d2b6e14df11bddc122e79c66f7e226e8916

build:
  number: 0
  script_env:
    - OUTPUT_PATH={{ target_gobin }}tilt{{ target_goexe }}

requirements:
  build:
    - {{ compiler('go') }}

    - {{ compiler('c') }}        # [unix]
    - {{ stdlib("c") }}          # [unix]
    - {{ compiler('cxx') }}      # [unix]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('m2w64_cxx') }}      # [win]

    - go-licenses
    - make
    - nodejs 20
    - yarn <2
  run_constrained:
    - {{ pin_compatible(compiler('c')) }}        # [unix]
    - {{ pin_compatible(compiler('cxx')) }}      # [unix]
    - {{ pin_compatible(compiler('m2w64_c')) }}        # [win]
    - {{ pin_compatible(compiler('m2w64_cxx')) }}      # [win]

test:
  commands:
    - tilt version

about:
  home: https://github.com/tilt-dev/tilt
  license: Apache-2.0
  license_file: LICENSE
  summary: A multi-service dev environment for teams on Kubernetes
  description: |
    Tilt automates all the steps from a code change to a new process: watching
    files, building container images, and bringing your environment up-to-date.

extra:
  recipe-maintainers:
    - joseph-zhong
    - nicks
