{% set version = "0.23.2" %}

package:
  name: tilt
  version: {{ version }}

source:
  url: https://github.com/tilt-dev/tilt/archive/v{{ version }}.tar.gz
  sha256: c6b76983b6a74411f3e8fc53ae3843139105e07c0ee6a1f5064b25c643ef1202

build:
  number: 0

requirements:
  build:
    - {{ compiler('go') }}
    - {{ compiler('cxx') }}
    - go-licenses
  run_constrained:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]

test:
  commands:
    - tilt version

about:
  home: https://github.com/tilt-dev/tilt
  license: Apache-2.0
  license_file: LICENSE
  summary: A multi-service dev environment for teams on Kubernetes
  description: |
    Tilt automates all the steps from a code change to a new process: watching
    files, building container images, and bringing your environment up-to-date.

extra:
  recipe-maintainers:
    - joseph-zhong
    - nicks
